### ISSUE TITLE
`clone_model` method doesn't follow keras API?

### ISSUE THREAD

**Issue by amn41** [matthiasplappert/keras-rl#10]
in `util.py` there is the line

`clone = Sequential.from_config(config,custom_objects)`

I can run the examples if I remove the second argument. But otherwise throws an error that 3 arguments are passed instead of 2. Should these be there?

**Comment by matthiasplappert** [comment]
Actually, never mind. I've temporarily removed passing custom_objects to `Sequential.from_config`. This should resolve it for now, if you don't use custom_objects. I'll properly fix this and add support to Keras for this later (about to go on vacation).
