### ISSUE TITLE
SARSAAgent does not use test_policy

### ISSUE THREAD

**Issue by hughdbrown** [matthiasplappert/keras-rl#100]
```
class SARSAAgent(Agent):
    """Write me
    """
    def __init__(self, model, nb_actions, policy=None, test_policy=None, gamma=.99, nb_steps_warmup=10,
                 train_interval=1, delta_clip=np.inf, *args, **kwargs):
        super(SarsaAgent, self).__init__(*args, **kwargs)

        # Do not use defaults in constructor because that would mean that each instance shares the same
        # policy.
        if policy is None:
            policy = EpsGreedyQPolicy()
        if test_policy is None:
            test_policy = GreedyQPolicy()

        self.model = model
        self.nb_actions = nb_actions
        self.policy = policy
        self.test_policy = policy
        self.gamma = gamma
        self.nb_steps_warmup = nb_steps_warmup
        self.train_interval = train_interval

        self.delta_clip = delta_clip
        self.compiled = False
        self.actions = None
        self.observations = None
        self.rewards = None
```

It looks like a typo to me. I am guessing you meant `self.test_policy = test_policy`.

**Comment by raopku** [comment]
please refer to the pull request whose title is Fix default policy handling of DQNAgent #70

**Comment by hughdbrown** [comment]
I am not sure what you are saying. Do you mean that the commit for #70 addresses the issue I am raising? Or do you mean this is an additional problem that #70 should deal with before that PR is accepted and merged?

As I see it, the commit for #70 does not fix the oversight/typo I am pointing to, if that's what you meant.

**Comment by matthiasplappert** [comment]
Yep, you are right, this was a typo. Has been fixed in https://github.com/matthiasplappert/keras-rl/commit/8b1940c5613e124a55d11ba257a8800bc12d65a5
