### ISSUE TITLE
Does Keras-rl pass its unit tests?

### ISSUE THREAD

**Issue by smgutstein** [matthiasplappert/keras-rl#129]
I have a recent implementation of keras-rl:

```
me@ARL--M6800:~/Downloads/keras-rl$ git pull origin master
From https://github.com/matthiasplappert/keras-rl
 * branch            master     -> FETCH_HEAD
Already up-to-date.
```
```
me@ARL--M6800:~/Downloads/keras-rl$ git log
commit a02079e86d5febfb469f26b478e2e2fe421284a8
Author: Matthias Plappert <matthiasplappert@me.com>
Date:   Sun Apr 9 15:06:42 2017 -0700

    Remove left over debug print statement

```

But, when I run the unit tests, I get the following results:

```
me@ARL--M6800:~/Downloads/keras-rl$ py.test ./tests/.
============================================================================== test session starts ===============================================================================
platform linux2 -- Python 2.7.6, pytest-2.8.7, py-1.4.31, pluggy-0.3.1 -- /usr/bin/python
cachedir: .cache
rootdir: /home/me/Downloads/keras-rl, inifile: pytest.ini
plugins: xdist-1.14, cov-2.2.1, pep8-1.0.6
gw0 I / gw1 I
[gw0] linux2 Python 2.7.6 cwd: /home/me/Downloads/keras-rl
[gw1] linux2 Python 2.7.6 cwd: /home/me/Downloads/keras-rl
[gw0] Python 2.7.6 (default, Oct 26 2016, 20:30:19)  -- [GCC 4.8.4]
[gw1] Python 2.7.6 (default, Oct 26 2016, 20:30:19)  -- [GCC 4.8.4]
gw0 [29] / gw1 [29]

scheduling tests via LoadScheduling
tests/integration/test_continuous.py::test_cdqn 
tests/integration/test_continuous.py::test_ddpg 
[gw1] FAILED tests/integration/test_continuous.py::test_ddpg 
tests/integration/test_discrete.py::test_double_dqn 
[gw0] FAILED tests/integration/test_continuous.py::test_cdqn 
tests/integration/test_discrete.py::test_dqn 
[gw0] FAILED tests/integration/test_discrete.py::test_dqn 
tests/integration/test_discrete.py::test_cem 
[gw0] PASSED tests/integration/test_discrete.py::test_cem 
tests/integration/test_discrete.py::test_sarsa 
[gw1] FAILED tests/integration/test_discrete.py::test_double_dqn 
tests/integration/test_discrete.py::test_duel_dqn 
[gw1] FAILED tests/integration/test_discrete.py::test_duel_dqn 
tests/rl/test_memory.py::test_training_flag
.
.
.
====================================================================== 7 failed, 22 passed in 47.97 seconds ======================================================================
 
```

The errors/failures fall into two classes:
1. rl/agents/ddpg.py:163: AttributeError (E AttributeError: 'Model' object has no attribute 'constraints') - 3 Times
2.../keras/keras/engine/training.py:959: TypeError (E   TypeError: get_updates() takes exactly 4 arguments (3 given)) - 4 Times

Are these known issues, or does Keras-rl fail its unit tests when run with Keras-2? I've already submitted a pull request that should fix the type error, but don't know if the problem (& therefore, the solution) are unique to me.

----------------------------------------------------------------------------------------------------------------------------------
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question in the [Keras-RL Google group](https://groups.google.com/forum/#!forum/keras-rl-users) or [join the Keras-RL Gitter channel](https://gitter.im/keras-rl/Lobby) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras-RL. You can update with:
`pip install git+git://github.com/matthiasplappert/keras-rl.git --upgrade --no-deps`

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps`

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short). If you report an error, please include the error message and the backtrace.

**Comment by linshiyx** [comment]
I got the same error.  Keras 2.0.7 removes the now-unused constraints attribute on layers and models.

**Comment by matthiasplappert** [comment]
I have looked into this and it is actually non-trivial to fix this while maintaining backwards compatibility to Keras < 2.0.7 and especially Keras 1. The current solution is thus to use Keras < 2.0.7 until I figure something out.
