### ISSUE TITLE
Keeping Keras-rl up to date?

### ISSUE THREAD

**Issue by ParthaEth** [matthiasplappert/keras-rl#152]
Since Matthias said that he is not any more using keras-rl as his own tool for research it (keras-rl) is rapidly getting outdated! Any plans on how to keep it alive? Lets have some discussion?

**Comment by cserpell** [comment]
There are many forks, but I don't know if anybody is really keeping it up to date.

**Comment by cserpell** [comment]
Indded, the discussion should be kept in #132 and we may close this issue.
