### ISSUE TITLE
Functional API Support

### ISSUE THREAD

**Issue by austinreiter** [matthiasplappert/keras-rl#32]
Hi,

This is fantastic--thanks so much for putting this together and out into the community!

I'm playing around with creating a custom Environment--and I'm trying to use Keras' Functional API that performs weight sharing, multiple inputs, merging of layers, etc.  If I have a CNN to estimate Q that takes multiple inputs, typically in keras you give a list of numpy arrays as input, and that works fine.  I was trying that here and it seems to not support that, is that correct?  I'm looking in dqn.py where the states are collected in forward() and then processed in batch in compute_q_values().

Do you know of a simple fix I can make to support this paradigm with your code?  Essentially giving a list of numpy arrays as input just as you might do with the Functional API in keras?  Or is that more complicated than it seems?

Thanks again!

**Comment by austinreiter** [comment]
Nevermind I answered my own question!  I can account for this in the Processor by reorganizing the state batch into a list and all works well.  Thanks!

(in case anyone else has this issue that's how you do it)

**Comment by matthiasplappert** [comment]
Yes, that's exactly how you're supposed to do it. I'll leave this issue open for now because this needs to be properly documented somewhere.

**Comment by StuartFarmer** [comment]
@austinreiter Can you share your code? Having the same issue, and an example would be phenomenal.

**Comment by austinreiter** [comment]
@StuartFarmer sure.  It's difficult to post all of my code but here's the gist.

I have a functional CNN setup that takes 3 inputs.  When i train normally I give it:

Xtrain = [X1, X2, X3] where each of X1, X2, and X3 are ntrainsamples x dims (and dims differs for each depending on what they are)

in the CNN definition, I have 3 different Input() layers for each of X1, X2, X3.

When you train the reinforcement learning here, internally it gets transformed into a single np array of lists of the 3 inputs.  So what you do is you write a Processor like this:

from rl.core import Processor

class MyProcessor(Processor):
	def __init__(self, batch_size):
		self.batch_size = batch_size
		self.b1 = None
		self.b2 = None
		self.b3 = None

	def process_observation(self, observation):
		# Don't do anything--I handle this elsewhere but you could do something here
		return observation

	def process_state_batch(self, batch):
		"""
		Here we "fix" the data to support the Functional API
		"""

		batch_size = batch.shape[0]

                # I treat this as a special case b/c during warmups it seems to always use a batch of 1,
                # but I know I'm being unnecessarily dumb here
		if batch_size == 1:
			return [np.expand_dims(batch[0,0,0],axis=0), np.expand_dims(batch[0,0,1],axis=0), np.expand_dims(batch[0,0,2],axis=0)]

                # You'll notice what's returned is the 3 individual numpy arrays are in the 3rd dimension
		d1 = batch[0,0,0].shape
		d2 = batch[0,0,1].shape
		d3 = batch[0,0,2].shape

                # I do this to make the allocation easier to manage and do it only once
		if self.b1 is None:
			self.b1 = np.zeros((batch_size,d1[0],d1[1]), dtype=batch.dtype)
		if self.b2 is None:
			self.b2 = np.zeros((batch_size,d2[0],d2[1]), dtype=batch.dtype)
		if self.b3 is None:
			self.b3 = np.zeros((batch_size,d3[0],d3[1]), dtype=batch.dtype)

		for i in range(batch_size):
			self.b1[i] = batch[i,0,0]
			self.b2[i] = batch[i,0,1]
			self.b3[i] = batch[i,0,2]

                # This is how we normally input into one of these multi-input functional CNNs
		return [self.b1, self.b2, self.b3]

	def process_reward(self, reward):
		# Don't do anything--I handle this elsewhere but you could do something here
		return reward



This all worked perfectly for me--I'm sure there are more elegant ways.  Hope this helps you!

**Comment by austinreiter** [comment]
@matthiasplappert Hi!

It looks like support for the functional API has been lost in one of the recent commits.  Any ideas on this?  Or is there something different I need to do?  I noticed that as of commit 534bfef6bddc0bec55fd43375b85b383d1b0a6ee it worked and sometime after that I get an error about a list of inputs.  Thanks!

**Comment by matthiasplappert** [comment]
Ops, sorry about that. That probably happened during the partial rewrite of DQN to make it more performant. Can you please post the full error message that you get?

**Comment by austinreiter** [comment]
Thanks @matthiasplappert.  This is the error I get:

File "build/bdist.linux-x86_64/egg/rl/agents/dqn.py", line 118, in compile
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.1-py2.7.egg/keras/engine/topology.py", line 1556, in __init__
    inputs_set = set(self.inputs)
TypeError: unhashable type: 'list'

The error happens when i call compile:

dqn.compile('rmsprop', metrics=['mae'])

**Comment by matthiasplappert** [comment]
Alright, I have just fixed it and this is now an official feature with tests. I've also included a generic processor, `MultiInputProcessor`, to make the conversion easier. The tests also serve as an example for this kind of stuff now, check out https://github.com/matthiasplappert/keras-rl/commit/4ce0cc4d1f9f686fefc2ee77f47c380b529426d7#diff-cdd218b42c7199c4a3df836e1bc61667R45 to see how to use DQN with multi-input and the new processor.

Let me know if you still run into problems.

**Comment by saksham15082** [comment]
@austinreiter I want to use a dqn to classify the MNIST dataset so what I am planning to do is input a feature representation of the image(as the state) and and the action space is the prediction from 0...9.I want to create a custom reward function and a custom next state to use in the bellman equation.Could you help me out with the code in terms of how to use the existing stuff in this repo.

**Comment by austinreiter** [comment]
@saksham15082 Hi--I'm not sure this would work or is well formed for the deep reinforcement learning problem.  Your input state (image) is not actually "acted" upon to change anything about the environment.  So OK on the first iteration, you input some representation of the image (or the image itself) into a CNN and the q-values are estimated.  The max represents the action to take (in this case, the digit class label), and then *what changes*?  Do you keep inputting the same image over and over?  In that case I think it just reduces to classification with some other penalty rather than soft-max.  

In any case to do this you just need to adapt the OpenAI Gym framework to basically re-implement the step() and reset() methods.  And then the keras-rl framework will easily retrofit to that inherited gym framework.  Hope this helps and good luck.
