### ISSUE TITLE
SequentialMemory() args/kwargs broken

### ISSUE THREAD

**Issue by RyanHope** [matthiasplappert/keras-rl#34]
You have some conflicts missmatch in args vs kwargs in Memory()/SequentialMemory()....

My code hits this error:

```
Traceback (most recent call last):
  File "dqn.py", line 102, in <module>
    main(args)
  File "dqn.py", line 72, in main
    memory = SequentialMemory(STEPS_PER_EPISODE*500)
  File "/home/ryan/workspace/keras-rl/rl/memory.py", line 107, in __init__
    super(SequentialMemory, self).__init__(**kwargs)
TypeError: __init__() takes at least 2 arguments (1 given)
```

And your examples hit this error:

```
Traceback (most recent call last):
  File "examples/cdqn_pendulum.py", line 65, in <module>
    memory = SequentialMemory(limit=100000, window_length=1)
TypeError: __init__() got an unexpected keyword argument 'window_length'
```

**Comment by matthiasplappert** [comment]
Are you sure that you've updated to the latest version of keras-rl? Running `examples/cdqn_pendulum.py` works fine here. The problem with the first error is that `window_length` now needs to be passed on initialization of the memory due to the way that things have been consolidated in the memory implementation.

**Comment by RyanHope** [comment]
guess when I do 'pip install .' in my keras-rl working dir it pulls from cache instead of the local dir, pointing it to the sdist I built does fix the second error

wrt the first error, I was aware that window_length moved to SequentialMemory from DQNAgent, but it had a default value in the latter
