### ISSUE TITLE
[Enhancement] Multiple output support

### ISSUE THREAD

**Issue by ekerazha** [matthiasplappert/keras-rl#39]
In keras-rl there are checks such as
```
if hasattr(actor.output, '__len__') and len(actor.output) > 1:
    raise ValueError('Actor "{}" has more than one output. DDPG expects an actor that has a single output.'.format(actor))
```
However we could have multiple outputs. For example, in this implementation https://yanpanlau.github.io/2016/10/11/Torcs-Keras.html there are 3 outputs (Steering, Acceleration, Brake).

In the paper about NAF https://arxiv.org/abs/1603.00748 they talk about a multi-target test (multi-target reacher).

 Do you plan to add multiple output support to keras-rl agents?

**Comment by matthiasplappert** [comment]
You can already have multiple actions, that is the output of the network can have dimension >= 1 (e.g. one action for the steering angle and one action for the acceleration). What is unsupported is that you have a graph model with more than one output layer. You can still use such models (e.g. if you want different activation functions for different actions) but you will have to merge them together into a concatenated output layer eventually.

Does that answer your question?

**Comment by ekerazha** [comment]
Yes. In this example https://yanpanlau.github.io/2016/10/11/Torcs-Keras.html there are different activation functions for different actions (logistic for [0, 1] actions and tanh for [-1, 1] actions).

**Comment by matthiasplappert** [comment]
Great, you should be able to get this to work by merging the different outputs together.

Let me know if you ever end up with a working version that uses keras-rl and learns to drive in Torcs. Would be super cool to add this as an example!
