### ISSUE TITLE
use keras-rl to my easy game

### ISSUE THREAD

**Issue by wwxFromTju** [matthiasplappert/keras-rl#42]
hi, matthiasplappert:
I think keras-rl is powerful and useful lib, gym also have many game, but if I want to use my own game, what function should I support? 
like:
env = mygame();
model.fit(env,.....)

I am a China student , so maybe my english is bad.

**Comment by RyanHope** [comment]
You need to make your game compliant with the OpenAI Gym spec.

**Comment by gorgitko** [comment]
Check this: https://github.com/matthiasplappert/keras-rl/issues/38

You only need to implement few OpenAI Gym methods for your game (or more formally, for your environment).
