### ISSUE TITLE
Episode reward does not include gamma

### ISSUE THREAD

**Issue by serteckian** [matthiasplappert/keras-rl#43]
Hi, thanks for this nice piece of work!

I am having some problems while learning my own environment. After training, the actions are always zero for any state. 

I've just started checking the code and have seen that the total episode reward does not include the discount factor gamma, i.e., in core.py lines 110 or 239 (methods fit() and test()) it writes
`episode_reward += reward`
However, I understand that we should count the number of steps, t, and then write
`episode_reward += pow(gamma, self.step)*reward`

Is this correct?

**Comment by matthiasplappert** [comment]
Hi, the `episode_reward` is just used for reporting. The actual algorithms use properly discounted rewards to estimate the Q values, for example (compare https://github.com/matthiasplappert/keras-rl/blob/master/rl/agents/dqn.py#L252).

Getting RL algorithms to work can often be quite tricky. Starting points are:
- Scale your inputs (i.e. the observations) such that they are all on the same scale and, preferably, have a mean of 0 and a variance of 1
- Experiment with different scales for your reward function. This can be especially problematic if your rewards are orders of magnitudes different throughout the game (i.e. very low rewards first and very large rewards in later stages of the env).

I hope that helps.

**Comment by serteckian** [comment]
Hi, thank you very much for your suggestion. 
My environment has linar constraints for the state-action space of the form Ax<=b, so that I have included a penalty function that squares the output if the constraints are violated. Hence, the rewards could be high at some point. But as you said, this may be an issue, so I am going to try another thing: I will consider any violated constraint as a terminal state with some fixed negative reward. 
Also, the state space is [0, 5]*ones(2,1) and the action space is [0, 0.5]*ones(4,1). I will try to shift and scale them.
