### ISSUE TITLE
Run OK in Pycharm but I got an error in console

### ISSUE THREAD

**Issue by serteckian** [matthiasplappert/keras-rl#44]
Hi, I am using the same conda environment for both console and Pycharm project. 
In Pycharm, the pendulum example runs without any trouble. However, when I try to run it remotely from console, it outputs an error.

$ python examples/ddpg_pendulum.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "examples/ddpg_pendulum.py", line 8, in <module>
    from rl.agents import DDPGAgent
ImportError: No module named 'rl'

I am sure this must be a trouble with my setup but, please, may you give me an idea what the problem might be?

Thanks!

**Comment by matthiasplappert** [comment]
Keras-RL is not installed. To fix this, activate the anaconda-Environment (http://conda.pydata.org/docs/using/envs.html#change-environments-activate-deactivate) and then simply install Keras-RL by running `python setup.py install`.

**Comment by serteckian** [comment]
Awesome! I was running the project from a shared folder and I thought it was already installed in the desktop, but it seems it wasn't. It works fine now. Thanks so much for your support!
