### ISSUE TITLE
Access to the complete history of states-actions-rewards in an episode

### ISSUE THREAD

**Issue by serteckian** [matthiasplappert/keras-rl#50]
Hi, 
The method agent.test returns history, which include the reward per episode. 
However, I would like to log the entire sequence of state-action-reward per episode. 

I have seen a pass statement in rl/callbacks.py (line 27):
`
def on_step_end(self, step, logs={}):
        pass
`
So that I understand that this functionality is not implemented yet, right? What would be the cleanest way to do it?

Thanks!

**Comment by RyanHope** [comment]
The easiest way to do this would be to extend the Processor class and override the process_step function, see https://github.com/matthiasplappert/keras-rl/blob/master/rl/core.py

**Comment by matthiasplappert** [comment]
What @RyanHope said is a good approach for this. I've also considered to add this feature by default to the history but have decided against it because this can be a LOT of data for complex environments that run for millions of steps.

**Comment by serteckian** [comment]
@RyanHope Thanks for the suggestion I will try that way. 

@matthiasplappert I think this is very useful for error analysis when testing the learned policy. I think I will parameterize the storing frequency, so  it can subsample the steps and stores just one step out every K steps.

Thanks again for your support!
