### ISSUE TITLE
Is there a way to use this for multi-agent environments?

### ISSUE THREAD

**Issue by hmate9** [matthiasplappert/keras-rl#53]
Can keras-rl be modified to work with multi-agent environments? For example could you teach the ghosts in PacMan to cooperate and catch the PacMan?

**Comment by matthiasplappert** [comment]
In theory that is definitely possible. However, there is currently no direct support for environments like that built into keras-rl. You could, however, of course create a custom environment that is shared across many agent instances, where each agent acts as a different entity. More concretely, you would need to create a custom, shared environment and a pool of agents, each on its own thread. Furthermore, you'd need to create an agent-specific wrapper for the shared environment that specifies which agent is currently taking an action.

Here's a quick sketch on how this could work:
```
class SharedEnv(object):
    def step(self, agent_idx, action):
        # TODO: perform that action and get the observation for the current agent. Make sure this is thread-safe
        return obs, reward, done, info
# TODO: implement reset() and the likes in similar fashion

class LocalEnv(Env):
    def __init__(self, shared, agent_idx):
        self.shared = shared
        self.agent_idx = agent_idx

    def step(self, action):
        return self.shared.step(self.agent_idx, action)
# TODO: implement the rest of the methods accordingly


shared = SharedEnv()
for agent_idx in range(nb_agents):
    env = LocalEnv(shared, agent_idx)
    agent = DQNAgent(env, ...)  # TODO: create an agent with the local env
    # TODO: run each agent on its own thread
```

**Comment by cserpell** [comment]
Could anyone elaborate on how make this work? I have been trying to do this, but after trying many different ways to configure agents, environments and launching threads at different points, I always manage to get a TensorFlow exception of the kind:
```
ValueError: Tensor Tensor("activation_2/Softmax:0", shape=(?, 4), dtype=float32) is not an element of this graph.
```

**Comment by cserpell** [comment]
Something interesting would be to start with an environment that allows different agents, such as [go](https://github.com/openai/gym/blob/master/gym/envs/board_game/go.py), and then generalize to others more complicated.

**Comment by lemonteaa** [comment]
Can you post a minimal example that reproduce the problem? You may also want to look at tensorflow/tensorflow#14356 - my guess is that somewhere a node is missed while assembling the tensorflow graph (during model compilation) but it is in the keras model and hence evaluated.

That being said, I think that in the long term it might be better to rethink the implicit architecture of this library/framework - the Agent class in particular - since reinforcement learning has developed a lots since the initial development of this library, and many novel, yet more complicated configurations have been proposed.

**Comment by benelot** [comment]
I have the same TensorFlow exception. I can check if I can easily create a minimal example to reproduce the problem.

**Comment by AxKo** [comment]
I'm also interested to use Keras-RL for multiagent training and just wanted to hear if there has been any progress on this issue ??

**Comment by benelot** [comment]
Well, the easiest way to train multiple agents is to make an env interface
which covers the "controls" of both agents. But then they are not separable
afterwards. Unfortunately, there is no other way to do this with Keras-RL.
You should use tensorforce or baselines for better results.

**Comment by bstriner** [comment]
The combined interface should work fine. You would just build separate models for each player and concatenate the actions in one single super-player. Could write a generic wrapper for that purpose and add to the framework.

**Comment by benelot** [comment]
Right, actually that is pretty simple to do.

**Comment by bstriner** [comment]
So sounds like we should add that to the task list. Something like the below with a lot of assertions and other details.

```
class MultiAgent(Agent):
  def __init__(self, agents):
    super(MultiAgent, self).__init__()
    self.agents=agents
  def forward(self, observation):
    return Concatenate()([agent.forward(observation) for agent in agents])
  def reset_states(self):
    for agent in self.agents:
      agent.reset_states()
   ...
```

**Comment by AxKo** [comment]
Let me see if I understand that correctly.
The new MultiAgent would be instantiated with a list of agents (e.g. DQNAgent) and its forward() function returns a list of the actions that the agents want to perform, given the current observation !?

But what would the fit() function of the MultiAgent look like? That seems to be the tricky bit.
Also, with that forward() implementation the agents act simultaneously and not one after the other. I mean after agent1 performs its action, the state (i.e. observation) changes and then agent2 would selects an action based on the new state.

Maybe, let me clarify what I meant in my original post with multiagent training. I like to learn some classical board games like reversi or TicTacToe. So two (or more) agents act one after the other, change the state through their actions and each one is training its own deep network.
Could that be done with MultiAgent ??

**Comment by benelot** [comment]
Yes. Just think of implementing a normal agent. The method which is called
when the env wants an action returns an action vector like in a normal
agent. Now, the MultiAgent, being actually a set of agents, will call each
of its sub-agents for an action given the same state and return the
concatenated action vectors. Your board game will have to ignore the
actions of the agents that are not on turn. That is your board logic then.
For a multiagent situation where every agent can move at the same time
(think Soccer game with different players), this will not require any env
logic.

**Comment by velochy** [comment]
For future reference to anyone who wants to do this: the blueprint provided by @bstriner is sound, but there are a few extra hurdles to overcome. Most notably, you need to implement and pass forward two attributes (training and step) and implement the compiled flag. 

I have a working example for sequential moves (instead of simultaneous ones) implemented at 
https://github.com/velochy/rl-bargaining/blob/master/interleaved.py in case it helps.

**Comment by dat-boris** [comment]
Also for future reference, based on @velochy 's work on I have added a `MultiAgent` class.

Part of the issue with this is that there's still no standard multi-agent environment https://github.com/openai/gym/issues/934 available (the closest I have found is @koulanurag work with https://github.com/koulanurag/ma-gym).   I have taken a try at adding the `MultiAgent` class which should be able to talk to ma-gym environment.

https://github.com/keras-rl/keras-rl/compare/master...dat-boris:add-multi-agent

I'm relatively new to multi-agent RL and would love to learn from feedback.

**Comment by yujia21** [comment]
> I have a working example for sequential moves (instead of simultaneous ones) implemented at
> https://github.com/velochy/rl-bargaining/blob/master/interleaved.py in case it helps.

Thanks for sharing! I have also adapted this code to allow for flexibility in when the turn ends for one player and starts for another (for sequential multiphased environments where each agent interacts multiple times with the environment before it is the next agent's turn).

https://github.com/yujia21/board_games_rl/blob/master/agents/interleaved.py
