### ISSUE TITLE
pull request Travis CI error when import theano

### ISSUE THREAD

**Issue by raopku** [matthiasplappert/keras-rl#72]
in my pull request ["add duel network to dqn"](https://github.com/matthiasplappert/keras-rl/pull/71)
when using theano backend, the Travis CI failed. However, I have checked that there is no problem when using theano in my computer. 
[here is the error log link](https://travis-ci.org/matthiasplappert/keras-rl/jobs/198489146). It seems like that something wrong with import theano

could anyone help me?

**Comment by matthiasplappert** [comment]
This is indeed strange. Let's figure this out directly in the pull request.
