### ISSUE TITLE
Add Python 3 compatibility

### ISSUE THREAD

**Issue by jorahn** [matthiasplappert/keras-rl#8]
Just changed a print function-call and use range instead of xrange to make keras-rl run on both python 2.7 and 3.5 for me. See pull requests https://github.com/matthiasplappert/keras-rl/pull/4, https://github.com/matthiasplappert/keras-rl/pull/5, https://github.com/matthiasplappert/keras-rl/pull/6, https://github.com/matthiasplappert/keras-rl/pull/7.

**Comment by matthiasplappert** [comment]
Addressed by the aforementioned PRs and https://github.com/matthiasplappert/keras-rl/commit/7d84b609b6983c0ac5d13ec817197674ee9ce66b.
