### ISSUE TITLE
error occured rl.agents.dqn.py method process_state_batch()

### ISSUE THREAD

**Issue by flybirp** [matthiasplappert/keras-rl#81]
when a parse a bit complex list in this method, this line of code "batch = np.array(batch)" throws a exception
the list_a contains 60 list_bs, and each list_b contain a ndarray with shape(1,2) and another ndarray with shape(1,7,60,1)
 
I know I can change the state given by my customized enviornment, in order to fit the program. But, the task I am dealing with does not give me such rights

so...
how can I change this "batch = np.array(batch)" ???

**Comment by matthiasplappert** [comment]
Checkout out `MultiInputProcessor` (https://github.com/matthiasplappert/keras-rl/blob/master/rl/core.py#L519). That may do what you need. If not, you can always write your own processor.
