### ISSUE TITLE
AttributeError: 'TimeLimit' object has no attribute '_action_set'

### ISSUE THREAD

**Issue by chenwuperth** [matthiasplappert/keras-rl#82]
Hi,

I am new to keras-rl, and when I tried to run the example "python examples/dqn_atari.py",  I got this error:

...
Training for 1750000 steps ...
Interval 1 (0 steps performed)
Traceback (most recent call last):
  File "examples/dqn_atari.py", line 125, in <module>
    dqn.fit(env, callbacks=callbacks, nb_steps=1750000, log_interval=10000)
  File "/Users/Chen/pyml/lib/python2.7/site-packages/rl/core.py", line 111, in fit
    observation, r, done, info = env.step(action)
  File "/Users/Chen/proj/DRL/gym/gym/core.py", line 110, in step
    observation, reward, done, info = self._step(action)
  File "examples/dqn_atari.py", line 60, in _step
    action = env._action_set[a]
AttributeError: 'TimeLimit' object has no attribute '_action_set'

If I replace the env._action_set[a] with env.env._action_set[a] (in fact, all occurrences of env inside the _step() function, see:
https://github.com/matthiasplappert/keras-rl/blob/master/examples/dqn_atari.py#L60

then it appears working all fine again, and it appears that the Wrapper class did not expose those functions from the "inner" env by default. So did I miss anything when I run it, or is this something you have encountered before?

Thanks
Chen.

**Comment by matthiasplappert** [comment]
Hi, apparently OpenAI Gym changed a method name (which was internal to begin with) and this broke the example. I've since removed this hacky code and switched to using a deterministic version of Breakout in https://github.com/matthiasplappert/keras-rl/commit/f816f0680f80d486a3ae943742def801519311a6. Just use that and it should be fine.
