### ISSUE TITLE
 no rewards when running different game using dqn_atari.py

### ISSUE THREAD

**Issue by gyang1011** [matthiasplappert/keras-rl#83]
Hello,

I have encountered a issue when I try to test out a different gym game called "Enduro-v0" using dqn_atari.py. For some reasons I only get zero reward for both episode reward and mean reward. The only part of the code that I change is the following:

     parser.add_argument('--env-name', type=str, default='Enduro-v0')

**Comment by matthiasplappert** [comment]
This means that the agent never discovers a state that yields a reward. However, since this is not an issue with the framework itself but rather a problem with an application, please refer to the Keras-RL Google group for further discussion: https://groups.google.com/forum/#!forum/keras-rl-users
