### ISSUE TITLE
DDPG with window_length > 1 fails to compile due to shape mismatch (?)

### ISSUE THREAD

**Issue by kfeeeeee** [matthiasplappert/keras-rl#93]
Trying to work with window lengts greater than 1, e.g. 

```
WINDOW_LENGTH = 4



model = Sequential()
model.add(Flatten(input_shape=(WINDOW_LENGTH,7,7,512)))
model.add(Dense(1024))
model.add(Activation('sigmoid'))
model.add(Dense(1024))
model.add(Activation('sigmoid'))
model.add(Dense(1024))
model.add(Activation('sigmoid'))
model.add(Dense(4, init = Zeros()))
model.add(Activation('sigmoid'))



nb_actions = 4
action_input = Input(shape=(WINDOW_LENGTH,nb_actions), name='action_input')
observation_input = Input(shape=(WINDOW_LENGTH,7,7,512), name='observation_input')
reshape1 = Reshape((WINDOW_LENGTH,512*7*7))(observation_input)
reshape2 = Reshape((WINDOW_LENGTH,4))(action_input)
x = concatenate([reshape2, reshape1])
x = Flatten()(x)
x = Dense(512)(x)
x = Activation('relu')(x)
x = Dense(512)(x)
x = Activation('relu')(x)
x = Dense(128)(x)
x = Activation('relu')(x)
x = Dense(64)(x)
x = Activation('relu')(x)
x = Dense(32)(x)
x = Activation('relu')(x)
x = Dense(1)(x)
x = Activation('linear')(x)
critic = Model(input=[action_input, observation_input], output=x)
#critic.summary()

memory = SequentialMemory(limit=5000000, window_length=WINDOW_LENGTH)
random_process = OrnsteinUhlenbeckProcess(size=nb_actions, theta=.15, mu=0., sigma=.3, n_steps_annealing=10000)
agent = DDPGAgent(nb_actions=nb_actions, actor=model, critic=critic, critic_action_input=action_input,
                  memory=memory, nb_steps_warmup_critic=10, nb_steps_warmup_actor=10,
                  random_process=random_process, gamma=.99, target_model_update=10)
agent.compile(Adam(lr=.001, clipnorm=1.), metrics=['mae'])
```

fails with

> ValueError                                Traceback (most recent call last)
> <ipython-input-34-93a85d145f10> in <module>()
>       4                   memory=memory, nb_steps_warmup_critic=1, nb_steps_warmup_actor=1,
>       5                   random_process=random_process, gamma=.99, target_model_update=20)
> ----> 6 agent.compile(Adam(lr=.001, clipnorm=1.), metrics=['mae'])
> 
> /home/venv3/lib/python3.5/site-packages/rl/agents/ddpg.py in compile(self, optimizer, metrics)
>     130                 combined_inputs.append(i)
>     131                 critic_inputs.append(i)
> --> 132         combined_output = self.critic(combined_inputs)
>     133         if K.backend() == 'tensorflow':
>     134             grads = K.gradients(combined_output, self.actor.trainable_weights)
> 
> /home/venv3/lib/python3.5/site-packages/keras/engine/topology.py in __call__(self, inputs, **kwargs)
>     552 
>     553             # Actually call the layer, collecting output(s), mask(s), and shape(s).
> --> 554             output = self.call(inputs, **kwargs)
>     555             output_mask = self.compute_mask(inputs, previous_mask)
>     556 
> 
> /home/venv3/lib/python3.5/site-packages/keras/engine/topology.py in call(self, inputs, mask)
>    1984             return self._output_tensor_cache[cache_key]
>    1985         else:
> -> 1986             output_tensors, _, _ = self.run_internal_graph(inputs, masks)
>    1987             return output_tensors
>    1988 
> 
> /home/venv3/lib/python3.5/site-packages/keras/engine/topology.py in run_internal_graph(self, inputs, masks)
>    2166                     if all([hasattr(x, '_keras_shape') for x in computed_tensors]):
>    2167                         if len(computed_tensors) == 1:
> -> 2168                             shapes = _to_list(layer.compute_output_shape(computed_tensors[0]._keras_shape))
>    2169                             uses_learning_phase = computed_tensors[0]._uses_learning_phase
>    2170                         else:
> 
> /home/venv3/lib/python3.5/site-packages/keras/layers/core.py in compute_output_shape(self, input_shape)
>     383     def compute_output_shape(self, input_shape):
>     384         return (input_shape[0],) + self._fix_unknown_dimension(
> --> 385             input_shape[1:], self.target_shape)
>     386 
>     387     def call(self, inputs):
> 
> /home/venv3/lib/python3.5/site-packages/keras/layers/core.py in _fix_unknown_dimension(self, input_shape, output_shape)
>     377             output_shape[unknown] = original / known
>     378         elif original != known:
> --> 379             raise ValueError(msg)
>     380 
>     381         return tuple(output_shape)
> 
> ValueError: total size of new array must be unchanged
> 

I am not completly sure, whether it is because of an error in network topology or if it is because of network construction in keras-rl core. Any hint or help is appreciated!

**Comment by ViktorM** [comment]
Btw can somebody explain what role window size is playing and in what situation it can be useful to set it large than 1?

**Comment by matthiasplappert** [comment]
Sorry for being so unresponsive right now. I'm about to relocate to a different country right now so everything is a bit busy and crazy. I'll try to get back to you next weekend.

**Comment by matthiasplappert** [comment]
This problem is related to your model setup. Your input action should not have a window length, that makes only sense for observations. To understand why, let me explain what the window length is intended for: in many environments, the state is not directly observable. For example in Atari, you only get an image of the current state. This does not contain all information that is important to play the game, for example the velocity of the ball. These properties can only be observed if we use a sequence of subsequent frames. This is precisely what window length controls: how many subsequent observations should be provided to the network?

You should thus remove the window length from the action input. You may also have to rework the concatenate code since you are now concatenating two completely different things. I'd suggest the following:

```
model = Sequential()
model.add(Flatten(input_shape=(WINDOW_LENGTH,7,7,512)))
model.add(Dense(1024))
model.add(Activation('sigmoid'))
model.add(Dense(1024))
model.add(Activation('sigmoid'))
model.add(Dense(1024))
model.add(Activation('sigmoid'))
model.add(Dense(4))
model.add(Activation('sigmoid'))



nb_actions = 4
action_input = Input(shape=(nb_actions,), name='action_input')
observation_input = Input(shape=(WINDOW_LENGTH,7,7,512), name='observation_input')
flattened_observations = Flatten()(observation_input)
x = concatenate([flattened_observations, action_input])
x = Dense(512)(x)
x = Activation('relu')(x)
x = Dense(512)(x)
x = Activation('relu')(x)
x = Dense(128)(x)
x = Activation('relu')(x)
x = Dense(64)(x)
x = Activation('relu')(x)
x = Dense(32)(x)
x = Activation('relu')(x)
x = Dense(1)(x)
x = Activation('linear')(x)
critic = Model(input=[action_input, observation_input], output=x)
#critic.summary()

memory = SequentialMemory(limit=5000000, window_length=WINDOW_LENGTH)
random_process = OrnsteinUhlenbeckProcess(size=nb_actions, theta=.15, mu=0., sigma=.3, n_steps_annealing=10000)
agent = DDPGAgent(nb_actions=nb_actions, actor=model, critic=critic, critic_action_input=action_input,
                  memory=memory, nb_steps_warmup_critic=10, nb_steps_warmup_actor=10,
                  random_process=random_process, gamma=.99, target_model_update=10)
agent.compile(Adam(lr=.001, clipnorm=1.), metrics=['mae'])
```

That should work and give you the desired behavior.

**Comment by kfeeeeee** [comment]
Thank you very much for your detailed explaination! Everything is clear now :+1:
