### ISSUE TITLE
using range or xrange

### ISSUE THREAD

**Issue by rola93** [matthiasplappert/keras-rl#96]
I'm running this code, but only with 8GB RAM, so I read it to see how to save some memory, and found than it always use range instead of xrange. Is there any reason for that? description here says it is for python 2.7. As far as I know, xrange uses less memory and is faster than range.

**Comment by matthiasplappert** [comment]
`xrange` has been removed from Python 3 so we have to use `range` instead to be compatible. However, in most cases this shouldn't be a problem since the lists returned by `range` have a pretty low memory footprint compared to the neural networks that you typically use with Keras-RL.
